package vessels;

public enum VesselDestination {
    KERBIN_LOCAL, KERBIN_LIMITED,
    MUN_LOCAL, MUN_LIMITED,
    MINMUS_LOCAL, MINMUS_LIMITED,
    DUNA_LOCAL, DUNA_LIMITED,
    IKE_LOCAL, IKE_LIMITED,
    EVE_LOCAL, EVE_LIMITED,
    GILLY_LOCAL, GILLY_LIMITED,
    JOOL_LOCAL, JOOL_LIMITED,
    LAYTHE_LOCAL, LAYTHE_LIMITED,
    VALL_LOCAL, VALL_LIMITED,
    TYLO_LOCAL, TYLO_LIMITED,
    BOP_LOCAL, BOP_LIMITED,
    POL_LOCAL, POL_LIMITED,
    DRES_LOCAL, DRES_LIMITED,
    EELOO_LOCAL, EELOO_LIMITED,
    KERBOL_LOCAL, KERBOL_LIMITED
}
