package vessels;

public enum VesselProperties {
    VTOL, SSRT, ELECTRIC, ION_POWERED, NO_CREW_SPACE, LANDER_CAPABLE, STATION_CAPABLE, ROVER_CAPABLE,
    SPACECRAFT_CAPABLE, WATERCRAFT_CAPABLE, WATER_LANDABLE, HAS_PARACHUTES, CARGO_SPACE
}
